### ISSUE TITLE
rdt flash error: Cannot assign to read only property 'name'

### ISSUE THREAD

**Issue by alexiri** [resin-io-modules/etcher-image-write#72]
Similarly to https://github.com/resin-os/resin-device-toolbox/issues/31, I'm getting the following error while trying to `rdt flash`:

```
 ~/resin > node --version
v6.9.1
~/resin > rdt version
0.0.6
 ~/resin > sudo DEBUG=* rdt flash resin.img 
TypeError: Cannot assign to read only property 'name' of function 'function createError(opts) {
        var result = new Error();

        Object.defineProperty(result, 'type', {...<omitted>... }'
    at extend (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/etcher-image-write/node_modules/error/node_modules/xtend/mutable.js:11:17)
    at TypedError (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/etcher-image-write/node_modules/error/typed.js:25:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/etcher-image-write/lib/errors.js:26:27)
    at Module._compile (module.js:570:32)
    at loader (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/etcher-image-write/lib/validate.js:24:16)
    at Module._compile (module.js:570:32)
    at loader (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/etcher-image-write/lib/index.js:26:16)
    at Module._compile (module.js:570:32)
    at loader (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Command.action (/usr/local/lib/node_modules/resin-device-toolbox/build/actions/flash.js:61:18)
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/command.js:96:21
    at Command.module.exports.Command.applyPermissions (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/command.js:41:14)
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/command.js:90:24
    at Command.module.exports.Command._checkElevation (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/command.js:61:14)
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/command.js:74:22
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/signature.js:174:14
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/node_modules/async/lib/async.js:269:32
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/build/signature.js:168:16
    at /usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/node_modules/async/lib/async.js:181:20
    at Immediate.iterate (/usr/local/lib/node_modules/resin-device-toolbox/node_modules/capitano/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

If you need help, or just want to say hi, don't hesitate in reaching out at:

        GitHub: https://github.com/resin-os/resin-device-toolbox/issues/new
        Gitter: https://gitter.im/resin-io/chat
```

This is on Ubuntu 16.04.1.

**Comment by jviotti** [comment]
Hm, I'm still unable to reproduce this issue, even on Ubuntu 16.04 running NodeJS v6.9.1.

One thought: could it be that your user's node version is v6.9.1, but once you prepend `sudo`, you run another (older) one? Maybe try `sudo node --version`?

**Comment by jviotti** [comment]
In any case, lets continue discussion in https://github.com/resin-os/resin-device-toolbox/issues/31, since this is an rdt specific problem.
